### PR TITLE
Capture the artifacts list of a variant and display them in the web ui

### PR DESCRIPTION
**Pull request by jawher**
screen shot 2015-05-17 at 20 01 28

### CODE REVIEW

**Comment by julienvey** [comment]
What is the behaviour when the artifact list is very long ?

**Comment by jawher** [comment]
I forgot to mention this, but I was planning to handle this (in the future), by implementing a file-browser like view where the user can navigate between folders if the artifacts list is above a certain threshold.

What was done here is the minimal viable product :)

**Comment by jawher** [comment]
I've limited the max height of the artifacts list and made it scrollable beyond it.

**Comment by julienvey** [comment]
Nice work !

**Pull request merged**
